# Generated by Django 4.1.1 on 2022-11-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Materials',
            new_name='Ingredient',
        ),
    ]
